# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Common configuration for all VMs
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Web server VMs
    config.vm.define "backend_service_01" do |backend_service_01|
      web01.vm.box = "ubuntu/bionic64"
      web01.vm.network "private_network", ip: "192.168.40.11"
      web01.vm.hostname = "backend_service_01"
    
    web01.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install python3
      sudo apt install python3-pip
      SHELL
    end
  
  
    # Database server VM
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.network "private_network",  ip: "192.168.40.12"
      db01.vm.hostname = "db01"
     
      # Provisioning script for db01
      db01.vm.provision "shell", inline: <<-SHELL
        yum install mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
        
        mysql -u root -e 'CREATE DATABASE wordpress;'

        mysql -u root -e 'GRANT SELECT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'

        mysql -u root -e 'FLUSH PRIVILEGES;'
        SHELL
    end
end
  
